name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install modules
      run: npm install

    - name: Run tests
      run: npm test
      
    - name: Package code
      run: |
        mkdir -p js
        sudo npm install -g browserify uglify-es
        browserify src/signum.js -o js/signum-bundle.js --standalone signum 
        uglifyjs js/signum-bundle.js -o js/signum-bundle.min.js --source-map "filename='js/signum-bundle.min.js.map',url='signum-bundle.min.js.map'"

    - name: Commit minified files
      uses: stefanzweifel/git-auto-commit-action@v4.1.6      
      with:
        repository: .
        file_pattern: js/*
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: ${{ github.ref }}
        
