# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install modules
      run: npm install

    - name: Run tests
      run: npm test
      
    - name: Package code
      run: |
        mkdir -p js
        mkdir -p tmp
        sudo npm install -g uglify-es
        cp src/*.js tmp 
        sed -i.bak '/require(".\//d' tmp/*  
        uglifyjs tmp/*.js -o js/signum.min.js --source-map "filename='js/signum.min.js.map',url='signum.min.js.map'"
        rm -r tmp

    - name: Commit minified files
      uses: stefanzweifel/git-auto-commit-action@v4.1.6      
      with:
        repository: .
        file_pattern: js/*
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: ${{ github.ref }}
        
