# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install modules
      run: sudo npm install --global

    - name: What is wrong?
      run: |
        npm list -g --depth=0
        npm bin -g
      
    - name: Run tests
      run: npm test
      
    - name: Minify code
      run: sudo minify-all /src

    - name: Arrange artifacts
      run: |
        mkdir -p /js
        cp /src/*.min.js /js 
          
    # Auto commits minified files to the repository
    # Ignore it if you don't want to commit the files to the repository 
    - name: Commit minified files
      uses: stefanzweifel/git-auto-commit-action@v4.1.6      
      with:
        repository: '/js'
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: ${{ github.ref }}
